name: Match
on:
  workflow_dispatch:
    inputs:
      engine1:
        description: 1st engine
        required: true
        default: stockfish-nnue.wasm@0.0.2-dev.7c1b679a
      engine2:
        description: 2nd engine
        required: true
        default: stockfish-nnue.wasm@1.0.0-dev.e3613959
      rounds:
        description: Number of rounds
        required: true
        default: 50
      concurrency:
        description: Concurrency of matches
        required: true
        default: 2
      time_control:
        description: Time control (e.g. 10+0.1, 60+0.6, etc...)
        required: true
        default: "60+0.6"
jobs:
  match:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.5.0"

      - name: Show settings
        run: >
          echo
          engine1=${{ github.event.inputs.engine1 }} engine2=${{ github.event.inputs.engine2 }}
          rounds=${{ github.event.inputs.rounds }} time_control=${{ github.event.inputs.time_control }}

      - name: Install tools
        run: >
          sudo apt-get update && sudo apt-get install -y qt5-default &&
          wget https://github.com/cutechess/cutechess/releases/download/1.2.0/cutechess_20200809+1.2.0+1.2.0-1_amd64.deb &&
          sudo dpkg -i cutechess_20200809+1.2.0+1.2.0-1_amd64.deb &&
          wget https://github.com/official-stockfish/books/raw/master/noob_3moves.epd.zip &&
          unzip noob_3moves.epd.zip

      - name: Install engines
        run: >
          npm install engine1@npm:${{ github.event.inputs.engine1 }} &&
          npm install engine2@npm:${{ github.event.inputs.engine2 }}

      - name: Run cutechess-cli
        run: >
          cutechess-cli
          -tournament round-robin
          -concurrency ${{ github.event.inputs.concurrency }}
          -rounds ${{ github.event.inputs.rounds }}
          -openings file=noob_3moves.epd format=epd policy=round -repeat -games 2
          -draw movenumber=40 movecount=4 score=10
          -resign movecount=4 score=1000
          -pgnout result-$(date +%F-%H-%M-%S).pgn
          -each proto=uci
          -engine tc=${{ github.event.inputs.time_control }} name=${{ github.event.inputs.engine1 }} cmd=node arg=$PWD/node_modules/engine1/uci.js
          -engine tc=${{ github.event.inputs.time_control }} name=${{ github.event.inputs.engine2 }} cmd=node arg=$PWD/node_modules/engine2/uci.js

      - uses: actions/upload-artifact@v2
        with:
          path: result-*.pgn
